# Generated by Django 4.1.7 on 2023-03-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='schema_name',
        ),
    ]
